export const cards = [
    // {
    //     _id: "63fc53491d1ddaeeaa621070",
    //     cardNumber: "185",
    //     printRun: "",
    //     brand: "Donruss Optic",
    //     category: "BASKETBALL_CARDS",
    //     id: "70ed2d41-9018-4e14-a76c-3b9cdc7168a3",
    //     name: "2020 Donruss Optic #185 Xavier Tillman Green Pulsar",
    //     subject: "Xavier Tillman",
    //     variety: "Green Pulsar",
    //     year: "2020-01-01T00:00:00.000Z",
    //     autograph: "",
    //     certNumber: "6870581",
    //     gradeNumber: "9.5",
    //     gradingCompany: "SGC",
    //     serial: "",
    //     currentlyHeld: true,
    //     groupName:
    //         "2020 Donruss Optic #185 Xavier Tillman Green Pulsar SGC 9.5",
    //     images: "https://onlyalt-images.s3.us-east-2.amazonaws.com/image/public/70ed2d41-9018-4e14-a76c-3b9cdc7168a3_front.png, https://onlyalt-images.s3.us-east-2.amazonaws.com/image/public/70ed2d41-9018-4e14-a76c-3b9cdc7168a3_back.png",
    //     listing_id: "",
    //     listing_state: "",
    //     listing_listPrice: null,
    //     listing_type: "",
    //     listing_typename: "",
    //     purchaseDate: "",
    //     currentConfidenceMetric: "",
    //     currentErrorLowerBound: "",
    //     currentErrorUpperBound: "",
    //     changeOverDay: "",
    //     changeOverDayPercent: "",
    //     changeOverWeek: "",
    //     changeOverWeekPercent: "",
    //     costBasis: "",
    //     date: "",
    //     latestValue: "",
    //     unrealizedGain: "",
    //     unrealizedGainPercent: "",
    //     notes: "",
    //     auctionHouse: "",
    //     buyItNowPrice: "",
    //     itemDetailUrl:
    //         "https://app.alt.xyz/item/70ed2d41-9018-4e14-a76c-3b9cdc7168a3?prev=%2Fportfolio",
    //     auctionHouse1: "",
    //     auctionType: "",
    //     date1: "",
    //     price: "",
    //     url: "",
    //     __v: 0,
    // },
    {
        _id: "63fc53491d1ddaeeaa62106f",
        cardNumber: "TT2",
        printRun: "",
        brand: "Topps Chrome Formula 1",
        category: "RACING_CARDS",
        id: "c4f52516-566d-423c-bdc4-782c2c607dd4",
        name: "2020 Topps Chrome Formula 1 #TT2 Valtteri Bottas Track Tags",
        subject: "Valtteri Bottas",
        variety: "Track Tags",
        year: "2020-01-01T00:00:00.000Z",
        autograph: "",
        certNumber: "1536164",
        gradeNumber: "9.5",
        gradingCompany: "SGC",
        serial: "",
        currentlyHeld: true,
        groupName:
            "2020 Topps Chrome Formula 1 #TT2 Valtteri Bottas Track Tags SGC 9.5",
        images: "https://onlyalt-images.s3.us-east-2.amazonaws.com/image/public/c4f52516-566d-423c-bdc4-782c2c607dd4_front.png, https://onlyalt-images.s3.us-east-2.amazonaws.com/image/public/c4f52516-566d-423c-bdc4-782c2c607dd4_back.png",
        listing_id: "",
        listing_state: "",
        listing_listPrice: null,
        listing_type: "",
        listing_typename: "",
        purchaseDate: "",
        currentConfidenceMetric: "",
        currentErrorLowerBound: "",
        currentErrorUpperBound: "",
        changeOverDay: "",
        changeOverDayPercent: "",
        changeOverWeek: "",
        changeOverWeekPercent: "",
        costBasis: "",
        date: "",
        latestValue: "",
        unrealizedGain: "",
        unrealizedGainPercent: "",
        notes: "",
        auctionHouse: "",
        buyItNowPrice: "",
        itemDetailUrl:
            "https://app.alt.xyz/item/c4f52516-566d-423c-bdc4-782c2c607dd4?prev=%2Fportfolio",
        auctionHouse1: "",
        auctionType: "",
        date1: "",
        price: "",
        url: "",
        __v: 0,
    },
];
