const t =   {
      "_id": "63fc53491d1ddaeeaa62106b",
      "cardNumber": "6",
      "printRun": "10",
      "brand": "Donruss Optic",
      "category": "BASKETBALL_CARDS",
      "id": "7f120b44-a5bf-4685-bcce-380bdd1159f9",
      "name": "2017 Donruss Optic #6 Jaylen Brown All Clear For Takeoff Gold /10",
      "subject": "Jaylen Brown",
      "variety": "All Clear For Takeoff Gold",
      "year": "2017-01-01T00:00:00.000Z",
      "autograph": "",
      "certNumber": "5184066",
      "gradeNumber": "10",
      "gradingCompany": "SGC",
      "serial": "7",
      "currentlyHeld": true,
      "groupName": "2017 Donruss Optic #6 Jaylen Brown All Clear For Takeoff Gold /10 SGC 10",
      "images": "https://onlyalt-images.s3.us-east-2.amazonaws.com/image/public/7f120b44-a5bf-4685-bcce-380bdd1159f9_front.png, https://onlyalt-images.s3.us-east-2.amazonaws.com/image/public/7f120b44-a5bf-4685-bcce-380bdd1159f9_back.png",
      "listing_id": "",
      "listing_state": "",
      "listing_listPrice": null,
      "listing_type": "",
      "listing_typename": "",
      "purchaseDate": "",
      "currentConfidenceMetric": "",
      "currentErrorLowerBound": "",
      "currentErrorUpperBound": "",
      "changeOverDay": "",
      "changeOverDayPercent": "",
      "changeOverWeek": "",
      "changeOverWeekPercent": "",
      "costBasis": "",
      "date": "",
      "latestValue": "",
      "unrealizedGain": "",
      "unrealizedGainPercent": "",
      "notes": "",
      "auctionHouse": "",
      "buyItNowPrice": "",
      "itemDetailUrl": "https://app.alt.xyz/item/7f120b44-a5bf-4685-bcce-380bdd1159f9?prev=%2Fportfolio",
      "auctionHouse1": "",
      "auctionType": "",
      "date1": "",
      "price": "",
      "url": "",
      "__v": 0
    },